# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170512_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.ManyToManyField(related_name='mentions', through='blogs.Post_Mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
